[package]
name = "nlpewee"
version = "0.1.0"
authors = ["Tom Panton <pantonshire@gmail.com>"]
edition = "2018"
license = "MIT"
description = "NLPewee gRPC client"

[dependencies]
tonic = "0.4"
prost = "0.7"
chrono = "0.4"

[build-dependencies]
tonic-build = "0.4"
